<?php
/**
 * Block registration and shared Interactivity API state.
 *
 * @package TFPG
 */

namespace TFPG;

defined( 'ABSPATH' ) || exit;

/**
 * Registers the three blocks and owns the server side of the `tfpg`
 * Interactivity API store that they share.
 */
final class Blocks {

	/**
	 * Interactivity API store namespace shared by all blocks.
	 */
	const STORE = 'tfpg';

	/**
	 * Counters used to give every router region on the page a stable id.
	 *
	 * @var array<string, int>
	 */
	private static $region_counters = array();

	/**
	 * Whether the shared store state has been initialised in this request.
	 *
	 * @var bool
	 */
	private static $state_initialized = false;

	/**
	 * Hooks registration into `init`.
	 */
	public static function init() {
		add_action( 'init', array( __CLASS__, 'register' ) );
	}

	/**
	 * Registers every block found in the build manifest.
	 *
	 * The manifest (generated by `wp-scripts build --blocks-manifest`) lets
	 * WordPress register all blocks without reading each block.json from disk.
	 */
	public static function register() {
		wp_register_block_types_from_metadata_collection(
			TFPG_DIR . 'build',
			TFPG_DIR . 'build/blocks-manifest.php'
		);
	}

	/**
	 * Returns a unique, render-order-stable id for a router region.
	 *
	 * The Interactivity Router matches regions between the current page and the
	 * fetched page by id, so ids must be identical for identical markup.
	 *
	 * @param string $type Region type, e.g. `grid` or `filter`.
	 * @return string
	 */
	public static function next_region_id( $type ) {
		self::$region_counters[ $type ] = ( self::$region_counters[ $type ] ?? 0 ) + 1;

		return self::STORE . '/' . $type . '-' . self::$region_counters[ $type ];
	}

	/**
	 * Initialises the shared store state and config, once per request.
	 *
	 * Called from each block's render callback, so the state is only printed on
	 * pages that actually contain one of the blocks. Derived values are
	 * closures so that directives render correctly on the server; the same
	 * getters are re-implemented in JS for the client.
	 */
	public static function init_store() {
		if ( self::$state_initialized ) {
			return;
		}
		self::$state_initialized = true;

		wp_interactivity_config(
			self::STORE,
			array(
				'params' => Query::params(),
			)
		);

		wp_interactivity_state(
			self::STORE,
			array(
				'filters'          => Query::get_active_filters(),
				'isLoading'        => false,
				'hasActiveFilters' => static function () {
					return (bool) array_filter( Query::get_active_filters() );
				},
				'isTermSelected'   => static function () {
					$context = wp_interactivity_get_context();
					$filters = Query::get_active_filters();

					return isset( $context['taxonomy'], $context['slug'], $filters[ $context['taxonomy'] ] )
						&& in_array( $context['slug'], $filters[ $context['taxonomy'] ], true );
				},
			)
		);
	}

	/**
	 * Resets per-request state. Useful for tests and CLI.
	 */
	public static function reset() {
		self::$region_counters   = array();
		self::$state_initialized = false;
	}
}
